### ISSUE TITLE
Rewritting

### ISSUE THREAD

**Issue by SCKelemen** [coderobin/AvalonEdit#1]
In order for this to be UWP/MVVM compliant, most of this code will need to be rewritten.

**Comment by xied75** [comment]
Based on my experiences on trying to get ngit work under UWP, sometimes working on the forked repo is 100 times harder than just start anew from scratch, when you are changing the targeting framework etc. In this case to adopt it to fit MVVM, which I'm not yet sure how easy is to accomplish. But let's see.

**Comment by xied75** [comment]
1, Would you want me to add you as a collaborator to the repo so that you can merge PR yourself?
2, Or do you prefer that we review each other's PR and leave me to merge?
3, Any other preferences you have over work flow, GitHub flow etc.?

**Comment by SCKelemen** [comment]
I don't care, you can just review the code. Then, I will have another set of eyes, leading to higher code quality. I would say, move the old code into a folder. Then create a new solution, SourceEditor, and we can start anew with that for UWP/MVVM
